# Databricks notebook source
# MAGIC %md
# MAGIC # 03 · Gold — dim_customer (SCD-1)
# MAGIC No history needed (spec): corrections simply overwrite. We MERGE the latest Silver
# MAGIC snapshot into the dimension so the surrogate key (`customer_sk`) stays **stable** across
# MAGIC daily runs while descriptive attributes are overwritten in place.
# MAGIC
# MAGIC * Business key: `customer_id`
# MAGIC * Surrogate key: `customer_sk` = xxhash64(customer_id)  (deterministic, stable)

# COMMAND ----------

# MAGIC %run ../04_utils/common_functions

# COMMAND ----------

# DeltaTable gives us the MERGE (upsert) API used below for SCD-1.
from delta.tables import DeltaTable

# Load the project config so table names are not hard-coded.
cfg = load_config()
cat = cfg["environment"]["catalog"]            # Unity Catalog name
silver = cfg["environment"]["silver_schema"]   # cleaned/conformed layer (input)
gold = cfg["environment"]["gold_schema"]        # star-schema layer (output)
# Fully-qualified source (Silver) and target (Gold) table names.
src = f"{cat}.{silver}.customers"
tgt = f"{cat}.{gold}.dim_customer"

# COMMAND ----------

# Build the latest snapshot of customers from Silver.
src_df = (
    read_delta(spark, src)
    .select(
        # Surrogate key: a stable integer id generated by hashing the business key.
        # xxhash64 is deterministic, so the same customer_id always maps to the same
        # customer_sk on every run -> the SK never changes (key requirement for joins).
        F.xxhash64(F.col("customer_id")).alias("customer_sk"),
        # Business key + descriptive attributes carried through to the dimension.
        "customer_id", "customer_unique_id", "customer_zip_code_prefix",
        "customer_city", "customer_state",
    )
    # Audit column: when this row was last processed.
    .withColumn("updated_ts", F.current_timestamp())
)

# COMMAND ----------

# First run: the dimension does not exist yet, so just write the full snapshot.
if not table_exists(spark, tgt):
    write_delta(src_df, tgt, mode="overwrite")
    print(f"Created {tgt} with {src_df.count():,} rows")
else:
    # Subsequent runs: SCD-1 upsert (MERGE) so the SK stays stable while attributes refresh.
    dim = DeltaTable.forName(spark, tgt)
    (
        # Match existing dim rows (t) to the new snapshot (s) on the business key.
        dim.alias("t")
        .merge(src_df.alias("s"), "t.customer_id = s.customer_id")
        # SCD-1: when a customer already exists, overwrite ALL columns in place
        # (no history kept — the old attribute values are simply lost).
        .whenMatchedUpdateAll()      # SCD-1 overwrite of changed attributes
        # When a customer is not yet in the dim, insert it as a brand-new row.
        .whenNotMatchedInsertAll()   # new customers
        .execute()
    )
    print(f"MERGE complete into {tgt}")

# COMMAND ----------

# Data-quality check: a dimension must have exactly one row per business key.
# If total rows != distinct customer_id count, the MERGE produced duplicates.
assert spark.table(tgt).count() == spark.table(tgt).select("customer_id").distinct().count(), "dup business key"
spark.sql(f"COMMENT ON TABLE {tgt} IS 'Gold dim_customer (SCD-1). Stable customer_sk, attributes overwritten on change.'")
display(spark.table(tgt).limit(5))
